version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WebAppDb=Server=webapp-db,1433;Database=WebAppDb;User Id=sa;Password=Test123!;Encrypt=False;
      - ConnectionStrings__AnalysisEngineDb=Server=analysisengine-db,1433;Database=AnalysisEngineDb;User Id=sa;Password=Test12345!;Encrypt=False;
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - webapp-db
      - analysisengine-db
      - rabbitmq
    networks:
      - app_network

  webapp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: webapp-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"
    networks:
      - app_network

  analysisengine-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: analysisengine-db
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Test12345!"
      ACCEPT_EULA: "Y"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
